### ISSUE TITLE
Some problems are still here

### ISSUE THREAD

**Issue by haha252** [Euphillya/Skyllia#10]
Problems are still here when i use the latest version(alpha-4).
i put it into the plugins floder but it still display alpha-3 
to upload the logs and configs to github, i change .toml to .txt.
and i deleted some identify information(such as passwords and IP address).
Hope to fix them!

[Config-Change it to 500.0.txt](https://github.com/Euphillya/Skyllia/files/13984903/Config-Change.it.to.500.0.txt)
[Logs-Change it to 500.0.log](https://github.com/Euphillya/Skyllia/files/13984905/Logs-Change.it.to.500.0.log)
[Config-Change it to 500.txt](https://github.com/Euphillya/Skyllia/files/13984906/Config-Change.it.to.500.txt)
[Logs-Change it to 500.log](https://github.com/Euphillya/Skyllia/files/13984907/Logs-Change.it.to.500.log)

**Comment by Euphillya** [comment]
Okay, that's strange because I thought I'd fixed it. I'm watching this in about 10 hours because I'm at work.
