### ISSUE TITLE
About Permission Node

### ISSUE THREAD

**Issue by haha252** [Euphillya/Skyllia#11]
Can we provide some information about permission nodes, so that we can use permission allocation plugins to assign permissions?
According to my recent test, I found that: if a new player joins the server, as long as we do not give him op permission, he has no permission to create a sky island.
Thank you!

**Comment by Euphillya** [comment]
I'll be working on the current wiki next week.

**Comment by haha252** [comment]
emmmm,is there any news of docs?
if there are something i can help, feel free to ask me~

**Comment by Euphillya** [comment]
> emmmm,is there any news of docs? if there are something i can help, feel free to ask me~

https://github.com/Euphillya/Skyllia/wiki/Permissions-Standard-du-Plugin-"Skyllia-Island"

**Comment by haha252** [comment]
thank you!
I may translate it to chinese
