### ISSUE TITLE
About Create An Island

### ISSUE THREAD

**Issue by haha252** [Euphillya/Skyllia#12]
I think we should give a certain amount of floating and slow falling effects when creating a sky island and teleporting the player to his sky island. Otherwise, it is easy to cause the errors in the video below:

https://github.com/Euphillya/Skyllia/assets/55837097/187dbc22-0617-483d-92e4-4959cbf782f9

as you see, i was transported below the island, and i fell to the void.QwQ.
Hope to add this function!

**Comment by Euphillya** [comment]
Try with this version : https://github.com/Euphillya/Skyllia/actions/runs/7593088995

**Comment by haha252** [comment]
ok, tp is sloved

**Comment by haha252** [comment]
but there is still some problems
