### ISSUE TITLE
Suggestion: skyllia.island.max_members permission

### ISSUE THREAD

**Issue by TheDiscordian** [Euphillya/Skyllia#29]
It'd be super useful to have a `skyllia.island.max_members.*` permission. Set like `skyllia.island.max_members.10` to limit a group's max members to 10 for example.

**Comment by Euphillya** [comment]
Verification already exists, but in database format. You can configure it with ``/skylliadmin setmaxmembers playerName value confirm``

**Comment by TheDiscordian** [comment]
Is there any way to do this with groups though? My intention for this feature would be to add the permission to groups in LuckPerms, where certain groups of users would automatically get higher or lower limits than others.

**Comment by Euphillya** [comment]
duplicate https://github.com/Euphillya/Skyllia/issues/30
