### ISSUE TITLE
Scheduled for Skyllia 1.0

### ISSUE THREAD

**Issue by Euphillya** [Euphillya/Skyllia#3]
The list is subject to change!

# Core : 

- [x] Folia support
- [x] Paper support https://github.com/Euphillya/SkyFolia/commit/2b8f9ffb147b6a03fa88409172983b3a867d617b
- [x] WorldEdit support (https://github.com/Euphillya/WorldEdit-Folia/releases/tag/7.3.0-SNAPSHOT-folia.1)
- [x] World without blocks https://github.com/Euphillya/SkyFolia/commit/f1e29771a8befacf4dace54a83b76bbfced0d324
- [x] Multiple world
- [x] Multisupport Version https://github.com/Euphillya/SkyFolia/commit/56859329638bce8b076800a098e53e58b0ab4763
- [x] Cache system https://github.com/Euphillya/SkyFolia/commit/09b78e241214697a1eae68dc3edc83e988224510

# Player orders to be created :

- [x] /is create [island] https://github.com/Euphillya/SkyFolia/commit/8e7346bd2cbac61041775a91f7b9ccf048a00ffe
- [x] /is delete https://github.com/Euphillya/SkyFolia/commit/6b2fb3901a0acb2ff41513339b86f36bc231cf83
- [x] /is demote [member] https://github.com/Euphillya/SkyFolia/commit/9b355f0403e61d4e5a5b4f835991630ab8f18bd8
- [x] /is promote [member] https://github.com/Euphillya/SkyFolia/commit/b461e5862ce9c52817e2aa12b80fca6a4196f627
- [x] /is invite <add/accept/decline> [player/owner] https://github.com/Euphillya/SkyFolia/commit/afd77ea334250ac4193e2ec57839cbd008a3c7d4 
- [x] /is kick [member] https://github.com/Euphillya/SkyFolia/commit/3997684191bc8870e9dd471b189498dceb505aff
- [x] /is leave https://github.com/Euphillya/SkyFolia/commit/c9bca3bc912f64f965d93ecafa3bbea3973e3afb
- [x] /is permissions [...] https://github.com/Euphillya/SkyFolia/commit/bba969fd4bfcf70903544a4ce22f19751a52dcce
- [x] /is access => old /is private https://github.com/Euphillya/SkyFolia/commit/52a00079b611a9b4c71fe061abc12234ca4942bc
- [x] /is biome [biome] https://github.com/Euphillya/SkyFolia/commit/9c41f041f3cba81b04ff189e5c2048156b4b50d3
- [x] /is home https://github.com/Euphillya/SkyFolia/commit/cf714ec7a97c5878de1335be24c70c74f184bf42
- [x] /is sethome https://github.com/Euphillya/SkyFolia/commit/cf714ec7a97c5878de1335be24c70c74f184bf42
- [x] /is [del/set]warp [warpName] https://github.com/Euphillya/SkyFolia/commit/1b0e2e3280dd31fad5a5c75c5b83061f1f243d7d
- [x] /is visit [player] https://github.com/Euphillya/SkyFolia/commit/4dff4ce285121b02dbf942e5baa1457612a87442
- [x] /is [un]ban [player] https://github.com/Euphillya/Skyllia/commit/4bcc6c21325a96e309f706dfd9f450a5d1a4db2f
- [x] /is expel [player] https://github.com/Euphillya/SkyFolia/commit/2606c031ddac1384b3df66995c644b8c8fc85e34
- [x] /is trust [player] https://github.com/Euphillya/Skyllia/commit/d78775236486edb55696224a1195518a9c26143e
- [x] /is untrust [player] https://github.com/Euphillya/Skyllia/commit/d78775236486edb55696224a1195518a9c26143e
- [x] - /is transfer [member]

Administrator commands to create : 

- [x] /is admin island setsize [1-255] confirm https://github.com/Euphillya/Skyllia/commit/990ee40242e75e30ed4a388412cad2be5ae60663
- [x] /skylliadmin forcedelete [player] confirm https://github.com/Euphillya/Skyllia/commit/7c63e3cd68c663ce124234dfc6f976a90b580aa6
- [x] /is admin island setmaxmember [owner] [1-max] confirm https://github.com/Euphillya/Skyllia/commit/4c92c02d458e7210d3d7b7aa87a3d593eb520b94

Permissions Plugins :

- [x] Permission per commandes
- [x] Permission visit ByPass https://github.com/Euphillya/SkyFolia/commit/4bc916203f1a32235b92bd389a924d414af686cf

# Permissions Role Settings :

- [x] Permission to break blocks https://github.com/Euphillya/SkyFolia/commit/09b78e241214697a1eae68dc3edc83e988224510
- [x] Permission to place blocks https://github.com/Euphillya/SkyFolia/commit/a8e53c350a8f1eb169395cac0c981ab02f57334f
- [x] Using buckets https://github.com/Euphillya/SkyFolia/commit/a8e53c350a8f1eb169395cac0c981ab02f57334f
- [x] Permission to open inventory https://github.com/Euphillya/SkyFolia/commit/a8e53c350a8f1eb169395cac0c981ab02f57334f
- [x] Promote a member https://github.com/Euphillya/SkyFolia/commit/b461e5862ce9c52817e2aa12b80fca6a4196f627
- [x] Demote a member https://github.com/Euphillya/SkyFolia/commit/9b355f0403e61d4e5a5b4f835991630ab8f18bd8
- [x] Close/Open island https://github.com/Euphillya/SkyFolia/commit/52a00079b611a9b4c71fe061abc12234ca4942bc
- [x] Delete/Create/TP warp https://github.com/Euphillya/SkyFolia/commit/1b0e2e3280dd31fad5a5c75c5b83061f1f243d7d
- [x] Ban a member https://github.com/Euphillya/Skyllia/commit/4bcc6c21325a96e309f706dfd9f450a5d1a4db2f
- [x] Expel a member https://github.com/Euphillya/SkyFolia/commit/2606c031ddac1384b3df66995c644b8c8fc85e34
- [x] PVP https://github.com/Euphillya/Skyllia/commit/64baa8edad340eccc867490234b744a7f587c645
- [x] Drop Items https://github.com/Euphillya/SkyFolia/commit/e5100eeb37f2135b68049bac3ed3f1492f4028f9
- [x] Take Items dropped https://github.com/Euphillya/SkyFolia/commit/e5100eeb37f2135b68049bac3ed3f1492f4028f9
- [x] Interact with all entities https://github.com/Euphillya/Skyllia/commit/bb23cef0a69c46f2c3955bcaef6f89521aca7db4
- [x] Kill Monster https://github.com/Euphillya/Skyllia/commit/64baa8edad340eccc867490234b744a7f587c645
- [x] Kill Animals https://github.com/Euphillya/Skyllia/commit/64baa8edad340eccc867490234b744a7f587c645
- [x] Managing warps https://github.com/Euphillya/SkyFolia/commit/1b0e2e3280dd31fad5a5c75c5b83061f1f243d7d
- [x] Managing trust https://github.com/Euphillya/Skyllia/commit/d78775236486edb55696224a1195518a9c26143e
- [x] Using portals https://github.com/Euphillya/SkyFolia/commit/e5100eeb37f2135b68049bac3ed3f1492f4028f9

# GamePlay : 

- [x] A nether portal to the nether world (Folia : https://github.com/Euphillya/SkyFolia/commit/e5100eeb37f2135b68049bac3ed3f1492f4028f9) (Paper : future)
- [x] An End portal takes you into the End (Folia : https://github.com/Euphillya/SkyFolia/commit/e5100eeb37f2135b68049bac3ed3f1492f4028f9) (Paper : future)

# Removed
- Ore generator
- is info = The best is to make an extension with PlaceHolderAPI or another to make your own custom /is info.
- is logs = Knowing that people will want to log in differently according to their wishes, I prefer to leave this functionality with an extension. The API could be further developed in the future to add a lot more!

**Comment by Euphillya** [comment]
If you have any ideas, post them here!

**Comment by haha252** [comment]
This is a very good plugin! Thank you very much for your development. If there are any Chinese and English wiki edits or plugin translations needed, feel free to mention me!

**Comment by haha252** [comment]
Shell we release some early access versions so we can find problems and fix them? I can’t wait to see this plugin running on the server!

**Comment by Euphillya** [comment]
> Shell we release some early access versions so we can find problems and fix them? I can’t wait to see this plugin running on the server!

I'll start releasing an alpha version when everything is checked off.

**Comment by Euphillya** [comment]
@haha252 https://github.com/Euphillya/SkyFolia/releases
