### ISSUE TITLE
Suggestion: skyllia.island.max_size/max_members permission

### ISSUE THREAD

**Issue by TheDiscordian** [Euphillya/Skyllia#30]
I hope this is not out of scope for this plugin, but it'd be amazing if there could be a permission to set the maximum size as a radius from the center of the island in blocks. For example `skyllia.island.max_size.160` would limit building further than than 160 blocks away from the center in any direction.

**Comment by Euphillya** [comment]
The modification already exists, but in the database. You can configure it with `/skylliadmin setsize playerName value confirm`

**Comment by TheDiscordian** [comment]
Is there any way to do this with groups though? My intention for this feature would be to add the permission to groups in LuckPerms, where certain users would automatically get higher or lower limits than others.

**Comment by Euphillya** [comment]
You can make island group authorizations with: ``skyllia.island.command.create.%s``

It works with island-settings

``toml
[island-settings]
	[island-settings.free]
		size = 50.0
		name = "basic
		max-members = 5
	[island-settings.premium1]
		size = 70.0
		name = "vip
		max-members = 10
```

**Comment by TheDiscordian** [comment]
Oh thank you! This isn't exactly what I wanted, but I still like it a lot.

For example if a user upgrades from free to VIP, they have to start a new island before they can invite more friends, no?

**Comment by Euphillya** [comment]
If you want to develop your own plugin, you can use this method that I've just set up.

https://github.com/Euphillya/Skyllia/commit/acca083a2072f9b34c1bfd0587206913cc8bd13b

**Comment by TheDiscordian** [comment]
> Either create a new island, or have a plugin that modifies Island#setMaxMembers(Integer), or do the command I put above.

The problem with commands is users can't do things without an admin being around or something, it's cleaner to use a permission group.

> If you want to develop your own plugin, you can use this method that I've just set up.
> 
> [acca083](https://github.com/Euphillya/Skyllia/commit/acca083a2072f9b34c1bfd0587206913cc8bd13b)

I appreciate it, I suppose if I can override things like `getMaxMembers` I can get it to check if a permission exists, and if so use the highest set value. I was mostly suggesting for this repo because it's convenient, and how my other plugins work.

If the suggestion won't be accepted this can probably be closed. Thanks a lot for your insight.

**Comment by Euphillya** [comment]
I prefer to create an Addon instead of modifying the code directly.
