### ISSUE TITLE
Changing Biome Seems to Hang Forever

### ISSUE THREAD

**Issue by TheDiscordian** [Euphillya/Skyllia#31]
Server: Paper: git-Paper-436
WorldEdit: 7.2.20
Skyllia: 1.0-RC5.1-all

When running `/island biome BADLANDS` for example, I get an in-progress message but after it seems to hang forever. I'm not sure how long this command is supposed to take, but after several minutes the biome doesn't change. Any further attempts gives an in-progress message.

**Comment by Euphillya** [comment]
https://github.com/Euphillya/Skyllia/commit/52308e8432eb4e08e4069dc633557bc5b80dd09b

**Comment by TheDiscordian** [comment]
Thank you I will test this tomorrow.

**Comment by TheDiscordian** [comment]
I found a moment to test today. Using the linked compiled build, I see no difference.

**Comment by Euphillya** [comment]
Fixed @TheDiscordian
