### ISSUE TITLE
Some questions.

### ISSUE THREAD

**Issue by 404forever1** [Euphillya/Skyllia#39]
1.How players become co_owner
2.I tried kick but it didn't work, so I want to know how to move the player out of member
3.Visitors cannot open the menu，Is it because of [inventory] permission that visitors cannot open the menu?
menu is zmenu，but command can work，item click dont work

**Comment by 404forever1** [comment]
Kick screenshot
![image](https://github.com/Euphillya/Skyllia/assets/168977890/137653c3-1974-4c87-92c4-a3d6797febcf)

**Comment by 404forever1** [comment]
[worlds.sky-overworld.portal-nether]
			enabled = false

**Comment by Euphillya** [comment]
1. skyllia promote player
2. I will check together 
3. Yes it's possible 
4. For the portal, create a new issues

**Comment by Euphillya** [comment]
Try with this version : https://github.com/Euphillya/Skyllia/actions/runs/9093608607

**Comment by 404forever1** [comment]
Still unable to open the menu
![image](https://github.com/Euphillya/Skyllia/assets/168977890/a72a84eb-945a-444a-a061-2fad63cb7acc)

**Comment by 404forever1** [comment]
Promote doesn't seem to be working properly.
![image](https://github.com/Euphillya/Skyllia/assets/168977890/50863c55-5db6-414c-8c37-ec1c2275f873)

**Comment by Euphillya** [comment]
> Still unable to open the menu ![image](https://private-user-images.githubusercontent.com/168977890/331052046-a72a84eb-945a-444a-a061-2fad63cb7acc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MzU0MDgsIm5iZiI6MTcxNTgzNTEwOCwicGF0aCI6Ii8xNjg5Nzc4OTAvMzMxMDUyMDQ2LWE3MmE4NGViLTk0NWEtNDQ0YS1hMDYxLTJmYWQ2M2NiN2FjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQwNDUxNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNmZjMjEzZWQ0MTk5OTg5Yjg1NDAxNzFhOTliYzJkYzZmMTI3OTkwNzRiNjk2NmJhY2M0ZmZkNTE0NTkwMzI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kuOvRNmMMHmA3tx0alJXEqLRn74x2eM8SxP3Q6QE6vc)

Try to contact developer to Zmenu

**Comment by Euphillya** [comment]
> Promote doesn't seem to be working properly. ![image](https://private-user-images.githubusercontent.com/168977890/331052232-50863c55-5db6-414c-8c37-ec1c2275f873.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MzU0MDgsIm5iZiI6MTcxNTgzNTEwOCwicGF0aCI6Ii8xNjg5Nzc4OTAvMzMxMDUyMjMyLTUwODYzYzU1LTVkYjYtNDE0Yy04YzM3LWVjMWMyMjc1Zjg3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQwNDUxNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzE4ZDIzODc2YWNlOWE0YzExZGEwNTQ2N2Y3ZWI4YjMwZTQ0MzJlZjViMjU1M2YwODRhMWE5NjE1ZDY2NzZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gDK0MDEXVKDy9QZxm-Rwp3FDgKE3fQRlPUWYhj059zA)

Strange, can you check in database if the player is correctly register

**Comment by 404forever1** [comment]
Players can't open boxes and so on in town, but the menu is normal.I don't think it's the menu. I believe the author will ignore me with such feedback.

**Comment by Euphillya** [comment]
In town ? My plugin only cancels if the player is on a skyblock island.

**Comment by 404forever1** [comment]
I mean, it works in cities and towns, but not in empty islands.

**Comment by 404forever1** [comment]
https://www.spigotmc.org/resources/zmenu-ultra-complete-menu-plugin.110402/

**Comment by Euphillya** [comment]
@404forever1 So after checking, the problem does not come from the Skyblock plugin. He should read his inventory instance last and if it is canceled, open it anyway. Adding a configuration to each inventory would be a very good idea!

**Comment by 404forever1** [comment]
What am I supposed to do?

**Comment by Euphillya** [comment]
contact the developer of your plugin.
