### ISSUE TITLE
portal-nether error

### ISSUE THREAD

**Issue by 404forever1** [Euphillya/Skyllia#40]
If the player builds and walks in, he will not be able to move at all
[worlds.sky-overworld.portal-nether]
enabled = false

**Comment by Euphillya** [comment]
Why can try this version : https://github.com/Euphillya/Skyllia/actions/runs/9205212246

**Comment by 404forever1** [comment]
Wait for the compatible menu plug-in, and then I will test

**Comment by 404forever1** [comment]
qwq

**Comment by Euphillya** [comment]
I'm fixed on last releases
