### ISSUE TITLE
Chinese language support

### ISSUE THREAD

**Issue by zixipurple** [Euphillya/Skyllia#46]
Can you add Chinese support to the plugin?
I have already translated all the text in language.toml into Chinese
You can refer to it
(请问您可以为插件添加中文吗？)
(我已经把language.toml的文本全部翻译成中文了)
(您可以参考一下)
[language.zip](https://github.com/user-attachments/files/16759827/language.zip)

**Comment by Euphillya** [comment]
It doesn't work in game?
